import { Button } from "@/components/ui/button";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import { useToken } from "@/hooks/useToken";
import { useAccount } from "wagmi";
import { Address, formatUnits } from "viem";
import { Loader2 } from "lucide-react";
import { useState, useEffect } from "react";
import { toast } from "sonner";

interface RevenueClaimDialogProps {
    tokenAddress: Address;
    tokenSymbol: string;
    tokenName: string;
}

export function RevenueClaimDialog({ tokenAddress, tokenSymbol, tokenName }: RevenueClaimDialogProps) {
    const {
        withdrawRevenue,
        usePendingRevenue,
        useTotalRevenuePerShare,
        useTotalSupply,
        isLoading: isTransactionLoading
    } = useToken();
    const { address } = useAccount();
    const [isOpen, setIsOpen] = useState(false);

    // Fetch data
    const { data: pendingRevenue, refetch: refetchPending } = usePendingRevenue(tokenAddress, address as Address);
    const { data: accRevenuePerShare } = useTotalRevenuePerShare(tokenAddress);
    const { data: totalSupply } = useTotalSupply(tokenAddress);

    const handleClaim = async () => {
        if (!address) return;
        const success = await withdrawRevenue(tokenAddress);
        if (success) {
            setIsOpen(false);
            refetchPending(); // Refresh pending revenue
        }
    };

    // Calculate approximate Total Revenue Distributed
    // Revenue Per Share is stored with 1e18 precision.
    // Total Revenue = (accRevenuePerShare * totalSupply) / 1e18
    const totalRevenue = (accRevenuePerShare && totalSupply)
        ? (BigInt(accRevenuePerShare) * BigInt(totalSupply)) / BigInt(1e18)
        : BigInt(0);

    const claimableAmount = pendingRevenue ? BigInt(pendingRevenue) : BigInt(0);

    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogTrigger asChild>
                <Button variant="outline" size="sm" className="bg-green-500/10 text-green-500 border-green-500/20 hover:bg-green-500/20 hover:text-green-400">
                    Claim Revenue
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Claim Revenue for {tokenName}</DialogTitle>
                    <DialogDescription>
                        View and withdraw your share of the revenue generated by this token.
                    </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                    <div className="flex flex-col gap-2 p-4 bg-muted/50 rounded-lg">
                        <span className="text-sm text-muted-foreground">Total Revenue Generated (Global)</span>
                        <span className="text-2xl font-bold font-mono">
                            ${Number(formatUnits(totalRevenue, 6)).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                        </span>
                    </div>
                    <div className="flex flex-col gap-2 p-4 bg-primary/10 rounded-lg border border-primary/20">
                        <span className="text-sm text-muted-foreground">Your Claimable Revenue</span>
                        <span className="text-3xl font-bold font-mono text-primary">
                            ${Number(formatUnits(claimableAmount, 6)).toLocaleString(undefined, { minimumFractionDigits: 4, maximumFractionDigits: 6 })}
                        </span>
                    </div>
                </div>
                <DialogFooter>
                    <Button
                        onClick={handleClaim}
                        disabled={claimableAmount <= BigInt(0) || isTransactionLoading}
                        className="w-full"
                    >
                        {isTransactionLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        {claimableAmount <= BigInt(0) ? "No Revenue to Claim" : "Withdraw Revenue"}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
